### ISSUE TITLE
doc: migration from the internal Playground to the hosted Playground

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcallhq.github.io#225]
## Description

Following our migration from the internal Playground to the Tailcall hosted Playground, many of our guides (such as the authentication guide) contain outdated screenshots and images. These need to be updated to reflect the new interface and features as per our hosted solution.

## Relevant Links
- Migration Details: [Issue #1790](https://github.com/tailcallhq/tailcall/issues/1790)
- Initial Documentation Update PR: [PR #224](https://github.com/tailcallhq/tailcallhq.github.io/pull/224)

## Tasks
- [ ] Review all guides and identify all the images that need updating.
- [ ] Capture new screenshots from the Tailcall hosted Playground that match the steps and descriptions in each guide.
- [ ] Update the images in the documentation.

**Comment by neo773** [comment]
/attempt #225

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;45 tailcallhq bounties <br/> + 68 bounties from 22 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvphens70004k009u7wrjbn3/cancel-attempt) |

**Comment by syedbarimanjan** [comment]
@neo773 you were working on the other issue and you still havent opened a pr for that what is this?

**Comment by neo773** [comment]
@syedbarimanjan 
Why are you surprised I declared my attempt one whole hour before you.
And please read Tailcall's bounty guidelines.

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan Why are you surprised I declared my attempt one whole hour before you. And please read Tailcall's bounty guidelines.

I am just saying that you could have said it that i cant do that one you should attempt it and you will do this one why do the same thing twice when we can colaborate?
